version: '2.4'

services:

  postgis:
    image: tobi312/rpi-postgresql-postgis:15-3.4-alpine
    container_name: postgis
    volumes:
      - ./postgis:/var/lib/postgresql/data
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
    environment:
       POSTGRES_PASSWORD: mysecretpassword
       #POSTGRES_DB: user
       #POSTGRES_USER: user
       #PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    ports:
      - 5432:5432
      #- 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:standalone
    container_name: adminer
    restart: unless-stopped
    environment:
       ADMINER_DEFAULT_SERVER: postgis
       ADMINER_DESIGN: nette
    ports:
      - 8080:8080
      #- 8080
    healthcheck:
      test:  wget --quiet --tries=1 --spider http://localhost:8080 || exit 1
      #test:  curl --fail http://localhost:8080 || exit 1  
      #start_period: 30s
      interval: 60s
      timeout: 5s
      retries: 5
