name: Build and Push debian-bookworm-slim Image

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
  schedule:
    - cron: '30 5 24 * *'  # At 05:30 on day-of-month 24.

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm/v7]  # 可支持的架构

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image debian-bookworm-slim
        uses: docker/build-push-action@v3
        with:
          context: ./debian-bookworm-slim
          file: ./debian-bookworm-slim/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/debian:bookworm-slim
          platforms: ${{ matrix.platform }}

     